### ISSUE TITLE
cssmenumaker not properly work  andriod phone

### ISSUE THREAD

**Issue by sreelalks** [cssmenumaker/jQuery-Plugin-Responsive-Drop-Down#1]
when scrolling the site menu will disappear

**Comment by tiberiualex** [comment]
Thank you for reporting this. It is a major bug and it will be fixed asap.

**Comment by tiberiualex** [comment]
Apparently, this is a problem encountered in Chrome for Android. Scrolling in this browser fires a window resize event. The plugin uses this event to change its design at a certain breakpoint, that's why the menu disappears. We already have a solution, but it needs more testing before we can update the repository.

**Comment by sreelalks** [comment]
Thanks for ur reply, we are waiting for this menu..

**Comment by tiberiualex** [comment]
We updated the plugin. Let us know if it fixes your problem.
